### ISSUE TITLE
Not detecting the test background

### ISSUE THREAD

**Issue by elterrasense** [rogeraabbccdd/SDVX-Wallpaper#1]
I've been looking for guides but I found no relevant info, also using any of the presets on the creator and drag/drop didn't work either.

**Comment by elterrasense** [comment]
Main issue was fixed, but it's not detecting the test background.

**Comment by rogeraabbccdd** [comment]
Hi, can you try latest version?

**Comment by elterrasense** [comment]
It only works if i rename it to `bg.webm`, changing it on Wallpaper Engine properties does nothing. Also the static background doesn't seem to have any effect overall.

Edit: Seems like nianoa's model breaks, Noah's model is missing textures.
![image](https://user-images.githubusercontent.com/19367314/78396674-0eda2680-75f0-11ea-833d-5c8fed23ab69.png)

**Comment by rogeraabbccdd** [comment]
There are two problems:
- I forgot to update `project.json` in 1491f958f24c9ccdfea7d731b2ad00c6c2c9b44e
- Nianoa has 2 textures, and I only load 1.

**Comment by rogeraabbccdd** [comment]
Everything should be fixed.
