### ISSUE TITLE
Failed to see the wallpaper after loading the index.html

### ISSUE THREAD

**Issue by konpoku** [rogeraabbccdd/SDVX-Wallpaper#11]
I can only see a whole black wallpaper without any video and live2d model.
I use Win11 system,live2d from KFC-2021083100,and the latest version of your wallpaper repo.
How can I get rid of this problem?

**Comment by dannylin0711** [comment]
Try enabling wallpaper engine debugging page in the setting, and goto http://localhost:1337, click the document link and make a screenshot.

**Comment by konpoku** [comment]
<img width="1280" alt="无标题" src="https://github.com/rogeraabbccdd/SDVX-Wallpaper/assets/58381542/c49a3f82-dde1-426f-bef1-a18f85dc2fb6">

**Comment by dannylin0711** [comment]
Okay, now head over to the Console tab on the right side, same, take a screenshot

**Comment by konpoku** [comment]
<img width="1163" alt="无标题" src="https://github.com/rogeraabbccdd/SDVX-Wallpaper/assets/58381542/f3cae39e-1b30-4446-b303-19d0bc6b3fc0">

**Comment by dannylin0711** [comment]
It is possibly because I was using newer game file as base for development, will try to fix it.

**Comment by konpoku** [comment]
okay,tks

**Comment by konpoku** [comment]
Using older version (2021 Aug 31st) I have solved this problem.
