### ISSUE TITLE
Only black screen appears

### ISSUE THREAD

**Issue by AyaseMitsukasa** [rogeraabbccdd/SDVX-Wallpaper#12]
I tried putting the live2d models from 2021083100 inside the repo folder
And putting the repo folder to wallpaper_engine\projects\myprojects
But after selecting the wallpaper in wallpaper engine
There only appears a black screen
It is weird since I think at least the default background or the background video will be displayed correctly even there is no live2d model right?
I also tried using the live2d models from 2021060802 but still no luck
Any help would be appreciated

**Comment by dannylin0711** [comment]
Download older version of this repository, current version needs newer models that doesn't exist in the version you given.

**Comment by AyaseMitsukasa** [comment]
> Download older version of this repository, current version needs newer models that doesn't exist in the version you given.

Thank you for the reply
May I know which newer version is required please
I want to try finding the resource out

**Comment by dannylin0711** [comment]
In commit message

**Comment by misaka00251** [comment]
20210831 + https://github.com/rogeraabbccdd/SDVX-Wallpaper/tree/ef510c503e4b7265d2fb4d6a42b24902b597d5c1 Works for me
