### ISSUE TITLE
Backgroud: Add Background MP4/H.264 Support.

### ISSUE THREAD

**Issue by DitFranXX** [rogeraabbccdd/SDVX-Wallpaper#3]
Seems like WebM hardware acceleration is not supported on WallpaperEngine 
(Source: https://steamcommunity.com/app/431960/discussions/2/1752358461531708214/)

Another suggestion that using MP4/H.264 helps performance(and also upload blocked when use webm): https://steamcommunity.com/app/431960/discussions/2/1629663905413056818/

**Comment by rogeraabbccdd** [comment]
MP4 is not working in web wallpaper.
https://steamcommunity.com/app/431960/discussions/2/3183345176707029464/#c3183345176707106711
